apiVersion: v1
kind: Service
metadata:
  name: coffee-catalog
spec:
  ports:
    - port: {{ .Values.coffeeCatalog.service.port }}
      targetPort: {{ .Values.coffeeCatalog.service.port }}
  selector:
    app: coffee-catalog