{{- if .Values.postgres.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.db | quote }}
{{- end }}
